export enum USER_REDUCER_ACTION {
  SET_USER_DATA = 'userReducer/SET_USER_DATA',
  SET_AUTH_STATE = 'userReducer/SET_AUTH_STATE',
  SET_CHANNEL_ID = 'userReducer/SET_CHANNEL_ID',
  SET_PROVIDER_ID = 'userReducer/SET_PROVIDER_ID',
  SET_USER_AVATAR = 'userReducer/SET_USER_AVATAR',
  SET_GLOBAL_LOADER = 'userReducer/SET_GLOBAL_LOADER',
  SET_IS_USER_DATA_SYNCHRONIZED = 'userReducer/SET_IS_USER_DATA_SYNCHRONIZED',
}
